apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unbound-chart.fullname" . }}
  labels:
    {{- include "unbound-chart.labels" . | nindent 4 }}
data:
  unbound.conf: |-
    server:
      verbosity: 1
      module-config: "validator cachedb iterator"
      statistics-interval: 600
      statistics-cumulative: yes

      # set to 0 to avoid warning message when cachedb module is loaded.
      # warning: cachedb: serve-expired-reply-ttl is set but not working for data originating from the external cache; 0 TLL is used for those.
      serve-expired-reply-ttl: 0

      interface: 0.0.0.0@53
      do-ip4: yes
      do-ip6: no
      do-udp: yes
      do-tcp: yes

      do-daemonize: no

      access-control: 0.0.0.0/0 allow

      directory: "/etc/unbound"
      logfile: ""
      pidfile: "/var/run/unbound/unbound.pid"

      identity: "NodeCloud_DNS_Service"
      # auto-trust-anchor-file: "/var/run/unbound/root.key"
      # tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt
      do-not-query-localhost: no

      num-threads: 4
      msg-cache-slabs: 4
      rrset-cache-slabs: 4
      infra-cache-slabs: 4
      key-cache-slabs: 4
      cache-min-ttl: 300
      cache-max-ttl: 86400
      rrset-cache-size: 256m
      msg-cache-size: 128m
      outgoing-range: 8192
      num-queries-per-thread: 4096
      # so-rcvbuf: 16m
      # so-sndbuf: 16m
      # so-reuseport: yes

      cachedb:
        backend: "redis"
        secret-seed: "default"
        redis-server-host: redis
        redis-server-port: 6379

      forward-zone:
        name: "."
        forward-addr: 127.0.0.1@5353
        # forward-tls-upstream: yes

          # https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers

          ## Cloudflare
          #forward-addr: 1.1.1.1@853#cloudflare-dns.com
          #forward-addr: 1.0.0.1@853#cloudflare-dns.com
          #forward-addr: 2606:4700:4700::1111@853#cloudflare-dns.com
          #forward-addr: 2606:4700:4700::1001@853#cloudflare-dns.com

          ## Cloudflare Malware
          # forward-addr: 1.1.1.2@853#security.cloudflare-dns.com
          # forward-addr: 1.0.0.2@853#security.cloudflare-dns.com
          # forward-addr: 2606:4700:4700::1112@853#security.cloudflare-dns.com
          # forward-addr: 2606:4700:4700::1002@853#security.cloudflare-dns.com

          ## Cloudflare Malware and Adult Content
          # forward-addr: 1.1.1.3@853#family.cloudflare-dns.com
          # forward-addr: 1.0.0.3@853#family.cloudflare-dns.com
          # forward-addr: 2606:4700:4700::1113@853#family.cloudflare-dns.com
          # forward-addr: 2606:4700:4700::1003@853#family.cloudflare-dns.com

          ## CleanBrowsing Security Filter
          # forward-addr: 185.228.168.9@853#security-filter-dns.cleanbrowsing.org
          # forward-addr: 185.228.169.9@853#security-filter-dns.cleanbrowsing.org
          # forward-addr: 2a0d:2a00:1::2@853#security-filter-dns.cleanbrowsing.org
          # forward-addr: 2a0d:2a00:2::2@853#security-filter-dns.cleanbrowsing.org

          ## CleanBrowsing Adult Filter
          # forward-addr: 185.228.168.10@853#adult-filter-dns.cleanbrowsing.org
          # forward-addr: 185.228.169.11@853#adult-filter-dns.cleanbrowsing.org
          # forward-addr: 2a0d:2a00:1::1@853#adult-filter-dns.cleanbrowsing.org
          # forward-addr: 2a0d:2a00:2::1@853#adult-filter-dns.cleanbrowsing.org

          ## CleanBrowsing Family Filter
          # forward-addr: 185.228.168.168@853#family-filter-dns.cleanbrowsing.org
          # forward-addr: 185.228.169.168@853#family-filter-dns.cleanbrowsing.org
          # forward-addr: 2a0d:2a00:1::@853#family-filter-dns.cleanbrowsing.org
          # forward-addr: 2a0d:2a00:2::@853#family-filter-dns.cleanbrowsing.org

          ## Quad9
          # forward-addr: 9.9.9.9@853#dns.quad9.net
          # forward-addr: 149.112.112.112@853#dns.quad9.net
          # forward-addr: 2620:fe::fe@853#dns.quad9.net
          # forward-addr: 2620:fe::9@853#dns.quad9.net

          ## getdnsapi.net
          # forward-addr: 185.49.141.37@853#getdnsapi.net
          # forward-addr: 2a04:b900:0:100::37@853#getdnsapi.net

          ## Surfnet
          # forward-addr: 145.100.185.15@853#dnsovertls.sinodun.com
          # forward-addr: 145.100.185.16@853#dnsovertls1.sinodun.com
          # forward-addr: 2001:610:1:40ba:145:100:185:15@853#dnsovertls.sinodun.com
          # forward-addr: 2001:610:1:40ba:145:100:185:16@853#dnsovertls1.sinodun.com